Replace base messages with rlang and cli
pharmaverse/sdtm.oak pull request #76
Opened 2024-07-26 06:54 UTC by galachad

- Replace base message with rlang
- Move vignette to package space
- Adds missing metadata in vignette

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull z
Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the 
[tidyverse style guide](https://style.tidyverse.org/). Run 
`styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should
consider realistic data scenarios and edge cases, e.g. empty datasets, errors,
boundary cases etc. - See 
[Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you 
fully follow the 
[deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords
and families. Refer to the 
[categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the
`NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it
has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build oak site `pkgdown::build_site()` and check that all affected
examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-07-28 17:06 UTC, ramiromagno requested changes
Hi @galachad:

- Can't we stick with `cli::cli_abort/warn/inform()` all across instead of `rlang::abort/warn/inform()`? Just for consistency.
- The S3 registration of  `mutate.cnd_df` is neither a mistake by you (it's a commit by me made earlier to this PR), nor it is an export of the function, but rather an S3 registration (see d6e3d92198ee9684dfb6f9d5c1f00b5408b93320). So think commit d0873ac3d1148c688f386a1d51a3c9d5b1a33f65 should be reverted.
- Locally, I still get the testthat snapshot blfl related issues when I run `devtools::check()` on this PR, so I am guessing that the CI/CD checking this PR is not using the latest admiraldev version, is it?

2024-07-29 14:35 UTC, galachad commented
Hi @ramiromagno 

The snapshot issue is fixed #73 or #75 we do not yet decide witch we are merge.

The different was coming from admiraldev package. 

For export of `mutate.cnd_df` thanks was pointing that out, I was thinking I exported that by the mistake. 

Let's use `cli` everywhere for the errors.

2024-07-29 15:17 UTC, ramiromagno approved these changes
All good.

2024-07-30 13:02 UTC, edgar-manukyan approved these changes

2024-07-30 14:53 UTC, merged